version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/bigants/Dockerfile
    command: gunicorn BiGAnts_web/wsgi.py:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/bigants/web/run/static
      - media_volume:/home/bigants/web/run/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/bigants/run/static
      - media_volume:/home/bigants/run/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: