version: '3.2'

services:
  web:
    build:
      context: .
      dockerfile: docker/bicon/Dockerfile
    command: gunicorn BiCoN_web.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_volume:/home/bicon/web/run/static
      - media_volume:/home/bicon/web/run/media
    networks:
      - bc_nginx_network
      - bc_database_network
      - bc_celery_network
    depends_on:
      - db

  celery:
    build:
      context: .
      dockerfile: docker/bicon/Dockerfile
    command: celery -A BiCoN_web worker -l info
    env_file:
      - .env
    volumes:
      - media_volume:/home/bicon/web/run/media
    networks:
      - bc_database_network
      - bc_celery_network
    depends_on:
      - db
      - rabbit

  db:
    image: postgres:12.0
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - bc_database_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - bc_celery_network
    #ports:
        #- "5672:5672"
    volumes:
      - rabbit_data:/var/lib/rabbitmq


  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/data/bicon/run/static
      - media_volume:/data/bicon/run/media
    # If you want the application to be listening on another port different than port 8000
    # Change the 'published' port number to the port you desire
    ports:
      - "${NGINX_PUBLISHED_PORT}:80"
    environment:
      - NGINX_PUBLISHED_PATH=${NGINX_PUBLISHED_PATH}
    networks:
      - bc_nginx_network
    depends_on:
      - web


networks:
  bc_nginx_network:
    driver: bridge
  bc_database_network:
    driver: bridge
  bc_celery_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data:
  rabbit_data:
