version: '3'

# all containers have access to a shared volume in /code. files that are modified by the celery container can be accessed from the django container etc.
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  # rabbitmq, needed for executing celery tasks.
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
        - "5672:5672"
